[workspace]
members = [
    "sandbox/address",
    "sandbox/profile",
    "registries/canister_registry",
    "registries/nft",
    "registries/tokens",
    "registries/address_book",
    "router",
    "template_registry",
    "proxy"
]